localaddr = ":8761"
loglevel = "DEBUG"
resolveraddr = "127.0.0.1:7777"
resolvertimeout = "10m"
resolvernotfoundtimeout = "10s"
concurrenttasks = 3 # number of concurrent must be less or equal to number of sessions in vfs
ingesttimeout = "10m"
ingestwait = "20s"

ffmpegpath = "/usr/local/bin/ffmpeg"
tempdir = "/mnt/c/temp/mediaserveringestvideo"

[ffmpegoutputcodec]
"web" = ["-c:v", "h264_nvenc", "-b:v", "1M", "-c:a", "aac", "-b:a", "128k", "-f", "mp4"]
"shots" = ["-f", "image2"]
"preview" = ["-t", "30", "-c:v", "h264_nvenc", "-b:v", "1M", "-c:a", "aac", "-b:a", "128k", "-f", "mp4"]

[grpcclient]
#mediaserverdb = "localhost:7653"

[log]
level = "debug"

[log.stash]
#logstash_host="sb-uwf4.swissbib.unibas.ch"
logstashhost="localhost"
logstashport=5046
logstashtracelevel="ERROR"
namespace="mediaserveringest"
dataset=""
#dataset="logs-mediaserver"
[log.stash.tls]
type="file"
cert="certs/ub-log.ub.unibas.ch.cert.pem"
key="certs/ub-log.ub.unibas.ch.key.pem"
ca=["certs/ca.crt"]
interval="1h"

[vfs.drivec]
name = "drivec"
type = "os"
[vfs.drivec.os]
basedir = "/mnt/c/Users/micro/Downloads"

[vfs.test]
name = "test"
type = "sftp"
[vfs.test.sftp]
address = "ub-x2go4.ub.p.unibas.ch:22"
user = "jumpuser"
privatekey = ["/mnt/c/daten/keys/syncthing/putty_ed25519.priv.openssh"]
basedir = "/digispace"
sessions = 3
zipasfoldercache = 2

[vfs.tests3]
name = "tests3"
type = "S3"
[vfs.tests3.S3]
AccessKeyID = "009145048a6e9c39de76"
SecretAccessKey = "%%TESTSECRET%%"
Endpoint = "s3-zh.lts.switch.ch"
Region = "zurich"
UseSSL = true
Debug = false
CAPEM = """-----BEGIN CERTIFICATE-----
MIIEyDCCA7CgAwIBAgIQDPW9BitWAvR6uFAsI8zwZjANBgkqhkiG9w0BAQsFADBh
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH
MjAeFw0yMTAzMzAwMDAwMDBaFw0zMTAzMjkyMzU5NTlaMFkxCzAJBgNVBAYTAlVT
MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxMzAxBgNVBAMTKkRpZ2lDZXJ0IEdsb2Jh
bCBHMiBUTFMgUlNBIFNIQTI1NiAyMDIwIENBMTCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAMz3EGJPprtjb+2QUlbFbSd7ehJWivH0+dbn4Y+9lavyYEEV
cNsSAPonCrVXOFt9slGTcZUOakGUWzUb+nv6u8W+JDD+Vu/E832X4xT1FE3LpxDy
FuqrIvAxIhFhaZAmunjZlx/jfWardUSVc8is/+9dCopZQ+GssjoP80j812s3wWPc
3kbW20X+fSP9kOhRBx5Ro1/tSUZUfyyIxfQTnJcVPAPooTncaQwywa8WV0yUR0J8
osicfebUTVSvQpmowQTCd5zWSOTOEeAqgJnwQ3DPP3Zr0UxJqyRewg2C/Uaoq2yT
zGJSQnWS+Jr6Xl6ysGHlHx+5fwmY6D36g39HaaECAwEAAaOCAYIwggF+MBIGA1Ud
EwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFHSFgMBmx9833s+9KTeqAx2+7c0XMB8G
A1UdIwQYMBaAFE4iVCAYlebjbuYP+vq5Eu0GF485MA4GA1UdDwEB/wQEAwIBhjAd
BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwdgYIKwYBBQUHAQEEajBoMCQG
CCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wQAYIKwYBBQUHMAKG
NGh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RH
Mi5jcnQwQgYDVR0fBDswOTA3oDWgM4YxaHR0cDovL2NybDMuZGlnaWNlcnQuY29t
L0RpZ2lDZXJ0R2xvYmFsUm9vdEcyLmNybDA9BgNVHSAENjA0MAsGCWCGSAGG/WwC
ATAHBgVngQwBATAIBgZngQwBAgEwCAYGZ4EMAQICMAgGBmeBDAECAzANBgkqhkiG
9w0BAQsFAAOCAQEAkPFwyyiXaZd8dP3A+iZ7U6utzWX9upwGnIrXWkOH7U1MVl+t
wcW1BSAuWdH/SvWgKtiwla3JLko716f2b4gp/DA/JIS7w7d7kwcsr4drdjPtAFVS
slme5LnQ89/nD/7d+MS5EHKBCQRfz5eeLjJ1js+aWNJXMX43AYGyZm0pGrFmCW3R
bpD0ufovARTFXFZkAdl9h6g4U5+LXUZtXMYnhIHUfoyMo5tS58aI7Dd8KvvwVVo4
chDYABPPTHPbqjc1qCmBaZx2vN4Ye5DUys/vZwP9BFohFrH/6j/f3IL16/RZkiMN
JCqVJUzKoZHm1Lesh3Sz8W2jmdv51b2EQJ8HmA==
-----END CERTIFICATE-----
"""
BaseUrl = ""
ZipAsFolderCache = 0

[vfs.testcache]
name = "testcache"
type = "S3"
[vfs.testcache.S3]
AccessKeyID = "AKIA312912CB2F7328D3"
SecretAccessKey = "%%TESTCACHESECRET%%"
Endpoint = "vip-ecs-ub.storage.p.unibas.ch"
Region = ""
UseSSL = true
Debug = false
BaseUrl = ""
ZipAsFolderCache = 0
CAPEM = """-----BEGIN CERTIFICATE-----
MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
/kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
nLRbwHOoq7hHwg==
-----END CERTIFICATE-----
"""

[client]
type = "dev"

[Indexer]
Enabled=true
# Enable this, if there are problem detecting length of audio files with ffmpeg
LocalCache=false

[Indexer.Checksum]
Enabled=true
Digest=["sha512"]

[Indexer.XML]
Enabled=true
[Indexer.XML.Format.document]
Attributes.xmlns = "http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml"
Type = "ocr"
Subtype = "FineReader10"
Mime = "application/xml"
[Indexer.XML.Format."mets:mets"]
Regexp = true
Attributes."xmlns:mets" = "^https?://www.loc.gov/METS/?$"
Type = "metadata"
Subtype = "METS"
Mime = "application/xml"


[Indexer.Siegfried]
Enabled=true
#Signature = "/usr/share/siegfried/default.sig"
#Signature = "file://C:/Users/micro/siegfried/default.sig"
Signature = "internal:/siegfried/default.sig"

# mapping of pronom id to mimetype if not found in siegfried
[Indexer.Siegfried.MimeMap]
"x-fmt/92" = "image/psd"
"fmt/134" = "audio/mp3"
"x-fmt/184" = "image/x-sun-raster"
"fmt/202" = "image/x-nikon-nef"
"fmt/211" = "image/x-photo-cd"
"x-fmt/383" = "image/fits"
"fmt/405" = "image/x-portable-anymap"
"fmt/406" = "image/x-portable-graymap"
"fmt/408" = "image/x-portable-pixmap"
"fmt/436" = "image/x-adobe-dng"
"fmt/437" = "image/x-adobe-dng"
"fmt/592" = "image/x-canon-cr2"
"fmt/642" = "image/x-raw-fuji"
"fmt/662" = "image/x-raw-panasonic"
"fmt/668" = "image/x-olympus-orf"
"fmt/986" = "text/xmp"
"fmt/1001" = "image/x-exr"
"fmt/1040" = "image/vnd.ms-dds"
"fmt/1781" = "image/x-pentax-pef"

# relevance of mimetype for sorting
# relevance < 100: rate down
# relevance > 100: rate up
# default = 100
[Indexer.MimeRelevance.1]
Regexp = "^application/octet-stream"
Weight = 1
[Indexer.MimeRelevance.2]
Regexp = "^text/plain"
Weight = 3
[Indexer.MimeRelevance.3]
Regexp = "^audio/mpeg"
Weight = 6
[Indexer.MimeRelevance.4]
Regexp = "^video/mpeg"
Weight = 5
[Indexer.MimeRelevance.5]
Regexp = "^application/vnd\\..+"
Weight = 4
[Indexer.MimeRelevance.6]
Regexp = "^application/rtf"
Weight = 4
[Indexer.MimeRelevance.7]
Regexp = "^application/.+"
Weight = 2
[Indexer.MimeRelevance.8]
Regexp = "^text/.+"
Weight = 4
[Indexer.MimeRelevance.9]
Regexp = "^audio/.+"
Weight = 5
[Indexer.MimeRelevance.10]
Regexp = "^video/.+"
Weight = 4
[Indexer.MimeRelevance.11]
Regexp = "^.+/x-.+"
Weight = 80

[Indexer.FFMPEG]
ffprobe = "ffprobe.exe"
wsl = false  # true, if executable is within linux subsystem on windows
timeout = "25s"
online = true
enabled = true
[[Indexer.FFMPEG.Mime]]
video = false
audio = true
format = "mov,mp4,m4a,3gp,3g2,mj2"
mime = "audio/mp4"
[[Indexer.FFMPEG.Mime]]
video = true
audio = true
format = "mov,mp4,m4a,3gp,3g2,mj2"
mime = "video/mp4"
[[Indexer.FFMPEG.Mime]]
video = true
audio = false
format = "mov,mp4,m4a,3gp,3g2,mj2"
mime = "video/mp4"

[Indexer.ImageMagick]
identify = "identify.exe"
convert = "convert.exe"
wsl = false  # true, if executable is within linux subsystem on windows
timeout = "480s"
online = true
enabled = true

[Indexer.Tika]
addressMeta = "http://localhost:9998/meta"
addressFulltext = "http://localhost:9998/tika"
#address = "http://localhost:9998/rmeta/text"
timeout = "10s"
regexpMimeFulltext = "^application/(pdf|vnd\\.oasis.opendocument.+|vnd\\.openxmlformats.+|vnd\\.ms-.+)" # "^.*$" # ""^application/.*$"  # regexp for mimetype, which are used for tika queries
regexpMimeFulltextNot = "" # "^.*$" # ""^application/.*$"
regexpMimeMeta = ""
regexpMimeMetaNot = "^(image|video|audio)/.*$"
online = true
enabled = true

